"""Add embedding column to Prompt

Revision ID: 0c8770d1d7bd
Revises: f68e4ba015ba
Create Date: 2025-12-10 01:20:52.830934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c8770d1d7bd'
down_revision: Union[str, Sequence[str], None] = 'f68e4ba015ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    def downgrade() -> None:
        op.drop_column('prompt', 'embedding')
    # ### end Alembic commands ###
